### ISSUE TITLE
Remove  Discord domains

### ISSUE THREAD

**Issue by astindev** [nextdns/piracy-blocklists#32]
Hello, could you remove the following streaming-video domains: `discord.gg` and `discord.com`, please?

**Comment by SergioGlorias** [comment]
> Hello, could you remove the following streaming-video domains: discord.gg and discord.com please?
and `discloudapp.com`

discord it's social network

**Comment by romaincointepas** [comment]
Fixed in https://github.com/nextdns/piracy-blocklists/commit/41d014a76cda410de2e4c207601f59767dc6285a.
